title: "> root@chacha"
description: >
   Passionate Self taught hacker...........
baseurl: ""
url: "https://chachamarwa.github.io/website/"
twitter_username: _The_Dust_
github_username:  chachaMarwa

# Build settings
markdown: kramdown
permalink: /posts/:title.html
